{-# OPTIONS --cubical #-}

open import Cubical.Foundations.Function
open import Cubical.Foundations.Prelude
open import Cubical.Foundations.HLevels
open import Cubical.Data.Prod.Base
open import Cubical.Algebra.Group.Base
open import Cubical.Algebra.Group.Properties
open import Cubical.Data.Bool.Base
open import Cubical.Data.Bool.Properties

data Quaternion : Type where
    e : Quaternion
    i : Quaternion
    j : Quaternion
    k : Quaternion
    -e : Quaternion
    -i : Quaternion
    -j : Quaternion
    -k : Quaternion

neg : Quaternion → Quaternion 
neg e = -e
neg i = -i
neg j = -j
neg k = -k
neg -e = e
neg -i = i
neg -j = j
neg -k = k 


mult : Quaternion → Quaternion → Quaternion
mult e y = y
mult i e = i
mult i i = -e
mult i j = k
mult i k = -j
mult i -e = -i
mult i -i = e
mult i -j = -k
mult i -k = j
mult j e = j
mult j i = -k
mult j j = -e
mult j k = i
mult j -e = -j
mult j -i = k
mult j -j = e
mult j -k = -i
mult k e = k
mult k i = j
mult k j = -i
mult k k = -e
mult k -e = -k
mult k -i = -j
mult k -j = i
mult k -k = e
mult -e y = neg (mult e y)
mult -i e = -i
mult -i i = e
mult -i j = -k
mult -i k = j
mult -i -e = i
mult -i -i = -e
mult -i -j = mult i j
mult -i -k = mult i k
mult -j e = -j
mult -j i = neg (mult j i)
mult -j j = neg (mult j j)
mult -j k = neg (mult j k)
mult -j -e = mult j e
mult -j -i = mult j i
mult -j -j = mult j j
mult -j -k = mult j k
mult -k e = -k
mult -k i = neg (mult k i)
mult -k j = neg (mult k j)
mult -k k = e
mult -k -e = k
mult -k -i = mult k i
mult -k -j = mult k j
mult -k -k = -e


QuaternionsToSet : Quaternion → (Bool × Bool × Bool)
QuaternionsToSet e = false , (false , false)
QuaternionsToSet i = false , (false , true)
QuaternionsToSet j = false , (true , false)
QuaternionsToSet k = false , (true , true)
QuaternionsToSet -e = true , (false , false)
QuaternionsToSet -i = true , (false , true)
QuaternionsToSet -j = true , (true , false)
QuaternionsToSet -k = true , (true , true)

SetToQuaternions : (Bool × Bool × Bool) → Quaternion 
SetToQuaternions (false , (false , false)) = e
SetToQuaternions (false , (false , true)) = i
SetToQuaternions (false , (true , false)) = j
SetToQuaternions (false , (true , true)) = k
SetToQuaternions (true , (false , false)) = -e
SetToQuaternions (true , (false , true)) = -i
SetToQuaternions (true , (true , false)) = -j
SetToQuaternions (true , (true , true)) = -k


postulate isSetBool×Bool×Bool : isSet (Bool × Bool × Bool)


embed : (x : Quaternion) → (SetToQuaternions (QuaternionsToSet x) ≡ x)
embed e = refl
embed i = refl
embed j = refl
embed k = refl
embed -e = refl
embed -i = refl
embed -j = refl
embed -k = refl

isSetQuaternion : isSet Quaternion 
isSetQuaternion = isSetRetract {B = (Bool × Bool × Bool)} QuaternionsToSet SetToQuaternions embed isSetBool×Bool×Bool


inv : Quaternion → Quaternion
inv e = e
inv -e = -e
inv x = neg x

assoc : (x y z : Quaternion) → (mult x (mult y z) ≡ mult (mult x y) z) 
assoc e y z = refl
assoc i e z = refl
assoc i i e = refl
assoc i i i = refl
assoc i i j = refl
assoc i i k = refl
assoc i i -e = refl
assoc i i -i = refl
assoc i i -j = refl
assoc i i -k = refl
assoc i j e = refl
assoc i j i = refl
assoc i j j = refl
assoc i j k = refl
assoc i j -e = refl
assoc i j -i = refl
assoc i j -j = refl
assoc i j -k = refl
assoc i k e = refl
assoc i k i = refl
assoc i k j = refl
assoc i k k = refl
assoc i k -e = refl
assoc i k -i = refl
assoc i k -j = refl
assoc i k -k = refl
assoc i -e e = refl
assoc i -e i = refl
assoc i -e j = refl
assoc i -e k = refl
assoc i -e -e = refl
assoc i -e -i = refl
assoc i -e -j = refl
assoc i -e -k = refl
assoc i -i e = refl
assoc i -i i = refl
assoc i -i j = refl
assoc i -i k = refl
assoc i -i -e = refl
assoc i -i -i = refl
assoc i -i -j = refl
assoc i -i -k = refl
assoc i -j e = refl
assoc i -j i = refl
assoc i -j j = refl
assoc i -j k = refl
assoc i -j -e = refl
assoc i -j -i = refl
assoc i -j -j = refl
assoc i -j -k = refl
assoc i -k e = refl
assoc i -k i = refl
assoc i -k j = refl
assoc i -k k = refl
assoc i -k -e = refl
assoc i -k -i = refl
assoc i -k -j = refl
assoc i -k -k = refl
assoc j e e = refl
assoc j e i = refl
assoc j e j = refl
assoc j e k = refl
assoc j e -e = refl
assoc j e -i = refl
assoc j e -j = refl
assoc j e -k = refl
assoc j i e = refl
assoc j i i = refl
assoc j i j = refl
assoc j i k = refl
assoc j i -e = refl
assoc j i -i = refl
assoc j i -j = refl
assoc j i -k = refl
assoc j j e = refl
assoc j j i = refl
assoc j j j = refl
assoc j j k = refl
assoc j j -e = refl
assoc j j -i = refl
assoc j j -j = refl
assoc j j -k = refl
assoc j k e = refl
assoc j k i = refl
assoc j k j = refl
assoc j k k = refl
assoc j k -e = refl
assoc j k -i = refl
assoc j k -j = refl
assoc j k -k = refl
assoc j -e e = refl
assoc j -e i = refl
assoc j -e j = refl
assoc j -e k = refl
assoc j -e -e = refl
assoc j -e -i = refl
assoc j -e -j = refl
assoc j -e -k = refl
assoc j -i e = refl
assoc j -i i = refl
assoc j -i j = refl
assoc j -i k = refl
assoc j -i -e = refl
assoc j -i -i = refl
assoc j -i -j = refl
assoc j -i -k = refl
assoc j -j e = refl
assoc j -j i = refl
assoc j -j j = refl
assoc j -j k = refl
assoc j -j -e = refl
assoc j -j -i = refl
assoc j -j -j = refl
assoc j -j -k = refl
assoc j -k e = refl
assoc j -k i = refl
assoc j -k j = refl
assoc j -k k = refl
assoc j -k -e = refl
assoc j -k -i = refl
assoc j -k -j = refl
assoc j -k -k = refl
assoc k e e = refl
assoc k i e = refl
assoc k j e = refl
assoc k k e = refl
assoc k -e e = refl
assoc k -i e = refl
assoc k -j e = refl
assoc k -k e = refl
assoc k e i = refl
assoc k i i = refl
assoc k j i = refl
assoc k k i = refl
assoc k -e i = refl
assoc k -i i = refl
assoc k -j i = refl
assoc k -k i = refl
assoc k e j = refl
assoc k i j = refl
assoc k j j = refl
assoc k k j = refl
assoc k -e j = refl
assoc k -i j = refl
assoc k -j j = refl
assoc k -k j = refl
assoc k e k = refl
assoc k i k = refl
assoc k j k = refl
assoc k k k = refl
assoc k -e k = refl
assoc k -i k = refl
assoc k -j k = refl
assoc k -k k = refl
assoc k e -e = refl
assoc k i -e = refl
assoc k j -e = refl
assoc k k -e = refl
assoc k -e -e = refl
assoc k -i -e = refl
assoc k -j -e = refl
assoc k -k -e = refl
assoc k e -i = refl
assoc k i -i = refl
assoc k j -i = refl
assoc k k -i = refl
assoc k -e -i = refl
assoc k -i -i = refl
assoc k -j -i = refl
assoc k -k -i = refl
assoc k e -j = refl
assoc k i -j = refl
assoc k j -j = refl
assoc k k -j = refl
assoc k -e -j = refl
assoc k -i -j = refl
assoc k -j -j = refl
assoc k -k -j = refl
assoc k e -k = refl
assoc k i -k  = refl
assoc k j -k  = refl
assoc k k -k = refl
assoc k -e -k  = refl
assoc k -i -k  = refl
assoc k -j -k  = refl
assoc k -k -k  = refl
assoc -e e e = refl
assoc -e e i = refl
assoc -e e j = refl
assoc -e e k = refl
assoc -e e -e = refl
assoc -e e -i = refl
assoc -e e -j = refl
assoc -e e -k = refl
assoc -e i e = refl
assoc -e i i = refl
assoc -e i j = refl
assoc -e i k = refl
assoc -e i -e = refl
assoc -e i -i = refl
assoc -e i -j = refl
assoc -e i -k = refl
assoc -e j e = refl
assoc -e j i = refl
assoc -e j j = refl
assoc -e j k = refl
assoc -e j -e = refl
assoc -e j -i = refl
assoc -e j -j = refl
assoc -e j -k = refl
assoc -e k e = refl
assoc -e k i = refl
assoc -e k j = refl
assoc -e k k = refl
assoc -e k -e = refl
assoc -e k -i = refl
assoc -e k -j = refl
assoc -e k -k = refl
assoc -e -e e = refl
assoc -e -e i = refl
assoc -e -e j = refl
assoc -e -e k = refl
assoc -e -e -e = refl
assoc -e -e -i = refl
assoc -e -e -j = refl
assoc -e -e -k = refl
assoc -e -i e = refl
assoc -e -i i = refl
assoc -e -i j = refl
assoc -e -i k = refl
assoc -e -i -e = refl
assoc -e -i -i = refl
assoc -e -i -j = refl
assoc -e -i -k = refl
assoc -e -j e = refl
assoc -e -j i = refl
assoc -e -j j = refl
assoc -e -j k = refl
assoc -e -j -e = refl
assoc -e -j -i = refl
assoc -e -j -j = refl
assoc -e -j -k = refl
assoc -e -k e = refl
assoc -e -k i = refl
assoc -e -k j = refl
assoc -e -k k = refl
assoc -e -k -e = refl
assoc -e -k -i = refl
assoc -e -k -j = refl
assoc -e -k -k = refl
assoc -i e e = refl
assoc -i e i = refl
assoc -i e j = refl
assoc -i e k = refl
assoc -i e -e = refl
assoc -i e -i = refl
assoc -i e -j = refl
assoc -i e -k = refl
assoc -i i e = refl
assoc -i i i = refl
assoc -i i j = refl
assoc -i i k = refl
assoc -i i -e = refl
assoc -i i -i = refl
assoc -i i -j = refl
assoc -i i -k = refl
assoc -i j e = refl
assoc -i j i = refl
assoc -i j j = refl
assoc -i j k = refl
assoc -i j -e = refl
assoc -i j -i = refl
assoc -i j -j = refl
assoc -i j -k = refl
assoc -i k e = refl
assoc -i k i = refl
assoc -i k j = refl
assoc -i k k = refl
assoc -i k -e = refl
assoc -i k -i = refl
assoc -i k -j = refl
assoc -i k -k = refl
assoc -i -e e = refl
assoc -i -e i = refl
assoc -i -e j = refl
assoc -i -e k = refl
assoc -i -e -e = refl
assoc -i -e -i = refl
assoc -i -e -j = refl
assoc -i -e -k = refl
assoc -i -i e = refl
assoc -i -i i = refl
assoc -i -i j = refl
assoc -i -i k = refl
assoc -i -i -e = refl
assoc -i -i -i = refl
assoc -i -i -j = refl
assoc -i -i -k = refl
assoc -i -j e = refl
assoc -i -j i = refl
assoc -i -j j = refl
assoc -i -j k = refl
assoc -i -j -e = refl
assoc -i -j -i = refl
assoc -i -j -j = refl
assoc -i -j -k = refl
assoc -i -k e = refl
assoc -i -k i = refl
assoc -i -k j = refl
assoc -i -k k = refl
assoc -i -k -e = refl
assoc -i -k -i = refl
assoc -i -k -j = refl
assoc -i -k -k = refl
assoc -j e e = refl
assoc -j e i = refl
assoc -j e j = refl
assoc -j e k = refl
assoc -j e -e = refl
assoc -j e -i = refl
assoc -j e -j = refl
assoc -j e -k = refl
assoc -j i e = refl
assoc -j i i = refl
assoc -j i j = refl
assoc -j i k = refl
assoc -j i -e = refl
assoc -j i -i = refl
assoc -j i -j = refl
assoc -j i -k = refl
assoc -j j e = refl
assoc -j j i = refl
assoc -j j j = refl
assoc -j j k = refl
assoc -j j -e = refl
assoc -j j -i = refl
assoc -j j -j = refl
assoc -j j -k = refl
assoc -j k e = refl
assoc -j k i = refl
assoc -j k j = refl
assoc -j k k = refl
assoc -j k -e = refl
assoc -j k -i = refl
assoc -j k -j = refl
assoc -j k -k = refl
assoc -j -e e = refl
assoc -j -e i = refl
assoc -j -e j = refl
assoc -j -e k = refl
assoc -j -e -e = refl
assoc -j -e -i = refl
assoc -j -e -j = refl
assoc -j -e -k = refl
assoc -j -i e = refl
assoc -j -i i = refl
assoc -j -i j = refl
assoc -j -i k = refl
assoc -j -i -e = refl
assoc -j -i -i = refl
assoc -j -i -j = refl
assoc -j -i -k = refl
assoc -j -j e = refl
assoc -j -j i = refl
assoc -j -j j = refl
assoc -j -j k = refl
assoc -j -j -e = refl
assoc -j -j -i = refl
assoc -j -j -j = refl
assoc -j -j -k = refl
assoc -j -k e = refl
assoc -j -k i = refl
assoc -j -k j = refl
assoc -j -k k = refl
assoc -j -k -e = refl
assoc -j -k -i = refl
assoc -j -k -j = refl
assoc -j -k -k = refl
assoc -k e e = refl
assoc -k i e = refl
assoc -k j e = refl
assoc -k k e = refl
assoc -k -e e = refl
assoc -k -i e = refl
assoc -k -j e = refl
assoc -k -k e = refl
assoc -k e i = refl
assoc -k i i = refl
assoc -k j i = refl
assoc -k k i = refl
assoc -k -e i = refl
assoc -k -i i = refl
assoc -k -j i = refl
assoc -k -k i = refl
assoc -k e j = refl
assoc -k i j = refl
assoc -k j j = refl
assoc -k k j = refl
assoc -k -e j = refl
assoc -k -i j = refl
assoc -k -j j = refl
assoc -k -k j = refl
assoc -k e k = refl
assoc -k i k = refl
assoc -k j k = refl
assoc -k k k = refl
assoc -k -e k = refl
assoc -k -i k = refl
assoc -k -j k = refl
assoc -k -k k = refl
assoc -k e -e = refl
assoc -k i -e = refl
assoc -k j -e = refl
assoc -k k -e = refl
assoc -k -e -e = refl
assoc -k -i -e = refl
assoc -k -j -e = refl
assoc -k -k -e = refl
assoc -k e -i = refl
assoc -k i -i = refl
assoc -k j -i = refl
assoc -k k -i = refl
assoc -k -e -i = refl
assoc -k -i -i = refl
assoc -k -j -i = refl
assoc -k -k -i = refl
assoc -k e -j = refl
assoc -k i -j = refl
assoc -k j -j = refl
assoc -k k -j = refl
assoc -k -e -j = refl
assoc -k -i -j = refl
assoc -k -j -j = refl
assoc -k -k -j = refl
assoc -k e -k = refl
assoc -k i -k = refl
assoc -k j -k = refl
assoc -k k -k = refl
assoc -k -e -k = refl
assoc -k -i -k = refl
assoc -k -j -k = refl
assoc -k -k -k = refl

IdR : (x : Quaternion) → mult x e ≡ x
IdR e = refl
IdR i = refl
IdR j = refl
IdR k = refl
IdR -e = refl
IdR -i = refl
IdR -j = refl
IdR -k = refl

IdL : (x : Quaternion) → mult e x ≡ x
IdL e = refl
IdL i = refl
IdL j = refl
IdL k = refl
IdL -e = refl
IdL -i = refl
IdL -j = refl
IdL -k = refl

InvR : (x : Quaternion) → mult x (inv x) ≡ e
InvR e = refl
InvR i = refl
InvR j = refl
InvR k = refl
InvR -e = refl
InvR -i = refl
InvR -j = refl
InvR -k = refl

InvL : (x : Quaternion) → mult (inv x) x ≡ e
InvL e = refl
InvL i = refl
InvL j = refl
InvL k = refl
InvL -e = refl
InvL -i = refl
InvL -j = refl
InvL -k = refl

QuaternionGroup = makeGroup {G = Quaternion} e mult inv isSetQuaternion assoc IdR IdL InvR InvL
 